const indicatorsDetails = {
    1: {
        title: "Número Efetivo de Partidos",
        indicator_purpose: "Calcula a dispersão e concentração do sistema partidário com base na distribuição das cadeiras no Legislativo. É um indicador importante para avaliar a saúde da democracia, pois um sistema partidário muito fragmentado pode dificultar a governabilidade e a formação de consensos. Permite comparações entre diferentes legislaturas.",
        how_to_interpretate: "O gráfico mostra a evolução do Número Efetivo de Partidos (NEPP) ao longo dos anos. Eixo X (horizontal): Representa os anos das eleições legislativas.\nEixo Y (vertical): Indica o NEPP, ou seja, quantos partidos, na prática, têm influência no Legislativo.",
        unit: "Número efetivo de partidos",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "NEPP",
    },
    2: {
        title: "Índice de Volatilidade Eleitoral",
        indicator_purpose: "Mede a instabilidade do sistema eleitoral, indicando o grau de fidelidade dos eleitores aos partidos. O índice reflete as mudanças na proporção de votos de cada partido entre eleições, considerando tanto ganhos quanto perdas.",
        how_to_interpretate: "Valores mais altos indicam maior instabilidade no apoio aos partidos; valores mais baixos sugerem fidelidade eleitoral. Eixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Índice de volatilidade eleitoral.",
        unit: "Volatilidade eleitoral",
        party_indicator: false,
        "indicator_t1": true,
        xAxisLabel: "Ano",
        yAxisLabel: "Índice de Volatilidade Eleitoral",
    },
    3: {
        title: "Quociente Eleitoral",
        indicator_purpose: "Representa o número de vagas conquistadas por um partido ou coligação sem considerar as cadeiras distribuídas por média. Esse indicador permite avaliar o desempenho eleitoral dos partidos e comparar sua eficiência ao longo do tempo.",
        how_to_interpretate: "A variação do quociente eleitoral ao longo do tempo pode indicar mudanças na representatividade e no peso do voto.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Quociente eleitoral.",
        unit: "Votos",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Quociente Eleitoral",
    },
    4: {
        title: "Quociente Partidário",
        indicator_purpose: "Representa o número de vagas conquistadas por um partido ou coligação sem considerar as cadeiras distribuídas por média. Esse indicador permite avaliar o desempenho eleitoral dos partidos e comparar sua eficiência ao longo do tempo.",
        how_to_interpretate: "A evolução do quociente partidário revela quais partidos conquistam mais vagas diretamente e quais dependem da distribuição por média.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Quociente partidário.",
        unit: "Quociente partidário",
        party_indicator: true,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Quociente Partidário",
    },
    5: {
        title: "Taxa de Renovação Líquida",
        indicator_purpose: "Mede a renovação do corpo legislativo ao longo do tempo. O índice considera todos os candidatos que tentaram a reeleição, destacando tanto os que foram reeleitos quanto os que não obtiveram sucesso.",
        how_to_interpretate: "Valores mais altos indicam maior renovação no Legislativo, enquanto valores mais baixos sugerem continuidade dos mesmos parlamentares.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (horizontal): Taxa de renovação líquida (%).",
        unit: "Porcentagem",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Taxa de Renovação Líquida(%)",
    },
    6: {
        title: "Taxa de Reeleição",
        indicator_purpose: "Mede a proporção de parlamentares que conseguem se reeleger para o mandato seguinte. Esse indicador é útil para analisar a profissionalização da política e os efeitos de reformas eleitorais.",
        how_to_interpretate: "Taxas mais altas indicam maior permanência de políticos no cargo, enquanto taxas mais baixas sugerem maior renovação legislativa.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Taxa de reeleição (%).",
        unit: "Porcentagem",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Taxa de Reeleição(%)",
    },
    7: {
        title: "Taxa de Migração Partidária",
        indicator_purpose: "Mede a média com que políticos mudam de partido ao longo de suas carreiras. Esse indicador reflete a fidelidade partidária e ajuda a entender o impacto de reformas eleitorais na estabilidade dos partidos e carreiras parlamentares.",
        how_to_interpretate: "Valores mais altos indicam maior troca de partidos entre os políticos, enquanto valores mais baixos sugerem maior fidelidade partidária.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Taxa de migração partidária (média de mudanças por político).",
        unit: "Média de migrações partidárias",
        party_indicator: false,
        "indicator_t1": true,
        xAxisLabel: "Ano",
        yAxisLabel: "Taxa de Migração Partidária",
    },
    8: {
        title: "Índice de Paridade Eleitoral de Gênero",
        indicator_purpose: "Mede a desigualdade de gênero na política ao comparar a proporção de candidatas e eleitas em cada eleição. Esse indicador permite avaliar o avanço da representatividade feminina e comparar diferentes cargos, regiões e esferas de governo.",
        how_to_interpretate: "Valores mais próximos de 1 indicam maior equilíbrio entre mulheres eleitas e candidatas, enquanto valores mais baixos mostram maior desigualdade de gênero.\n\nEixo Y: Índice de Paridade Eleitoral de Gênero (IPEG).\nBarras: Cada barra representa uma eleição.",
        unit: "IPEG",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "IPEG",
    },
    9: {
        title: "Distribuição de Votos por Região",
        indicator_purpose: "Mede as diferenças regionais nas preferências políticas e eleitorais com base na concentração de votos em cada região. Esse indicador ajuda a entender desigualdades regionais e a influência de fatores locais nas eleições.",
        how_to_interpretate: "Valores mais altos indicam maior concentração de votos em uma região específica. Valores mais baixos sugerem uma distribuição mais equilibrada dos votos entre regiões. A evolução ao longo do tempo pode mostrar mudanças nas bases eleitorais dos partidos e candidatos.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Índice de Concentração Regional do Voto (%).\nLinhas: Cada linha representa uma região.",
        unit: "Porcentagem",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Distribuição de Votos por Região (%)",
    },
    10: {
        title: "Índice de Concentração Regional do Voto",
        indicator_purpose: "Mede a concentração de votos em determinadas regiões, identificando áreas com maior hegemonia de um partido ou candidato. Esse indicador permite comparações regionais e ao longo do tempo.",
        how_to_interpretate: "Valores mais altos indicam maior concentração de votos em poucos partidos ou candidatos. Valores mais baixos sugerem uma distribuição mais equilibrada dos votos entre diferentes opções políticas. A evolução do índice pode revelar tendências de fortalecimento ou enfraquecimento de partidos em regiões específicas.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Índice de Concentração Regional do Voto (HHI).\nLinhas: Cada linha representa uma região (Estado, Município).",
        unit: "Índice de Herfindahl-Hirschman (HHI)",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Índice de Concentração Regional do Voto",
    },
    11: {
        title: "Índice de Dispersão do Voto",
        indicator_purpose: "Mede como os votos de partidos ou candidatos estão distribuídos geograficamente dentro de uma área eleitoral. Esse indicador ajuda a identificar concentrações ou dispersões de votos, revelando possíveis desigualdades regionais e padrões eleitorais.",
        how_to_interpretate: "\nPode ajudar a identificar efeitos de fatores como gerrymandering e clientelismo na distribuição eleitoral. Valores mais altos indicam uma distribuição mais equilibrada dos votos entre diferentes regiões. Valores mais baixos sugerem que os votos estão concentrados em áreas específicas.\n\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Índice de Dispersão Regional do Voto.\nLinhas: Cada linha representa uma região.",
        unit: "Coeficiente de variação",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Índice de Dispersão do Voto",
    },
    12: {
        title: "Índice de Eficiência do Voto",
        indicator_purpose: "Avalia a capacidade dos partidos de converter votos em cadeiras no Legislativo. Esse indicador permite identificar quais partidos são mais eficientes na mobilização do eleitorado e como fatores como fragmentação partidária e sistema eleitoral influenciam essa conversão.",
        how_to_interpretate: "\nA evolução do índice ao longo do tempo pode revelar mudanças na estratégia eleitoral dos partidos.Valores mais altos indicam maior eficiência na conversão de votos em cadeiras.\nValores mais baixos sugerem que um partido recebe muitos votos, mas conquista poucas cadeiras.\n\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Índice de Eficiência do Voto (IEV).\nLinhas: Cada linha representa um partido ou coligação/federação.",
        unit: "IEV",
        party_indicator: true,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Índice de Eficiência do Voto",
    },
    13: {
        title: "Taxa de Custo por Voto",
        indicator_purpose: "Mede a eficiência do financiamento de campanha ao calcular quanto um partido gastou, em média, para cada voto recebido. Esse indicador permite avaliar a transparência, equidade e impacto dos recursos financeiros na competitividade eleitoral.",
        how_to_interpretate: "A evolução do índice pode refletir mudanças nas regras de financiamento, estratégias de campanha ou influência do financiamento privado. Valores mais baixos indicam maior eficiência na conversão de recursos financeiros em votos. Valores mais altos sugerem que um partido ou candidato gastou mais para conquistar cada voto.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Taxa de Custo por Voto.\nLinhas: Cada linha representa um candidato ou partido.",
        unit: "Custo médio do voto em real",
        party_indicator: true,
        "indicator_t1": true,
        xAxisLabel: "Ano",
        yAxisLabel: "Taxa de Custo por Voto",
    },
    14: {
        title: "Índice de Igualdade de Acesso a Recursos",
        indicator_purpose: "Mede o grau de equidade no acesso a recursos financeiros entre candidatos em um sistema eleitoral. Esse indicador ajuda a identificar desigualdades que podem impactar a competitividade eleitoral e o equilíbrio do processo democrático.",
        how_to_interpretate: "A evolução do índice pode refletir mudanças nas regras de financiamento de campanhas e na distribuição de recursos públicos e privados. Valores mais altos indicam maior equidade na distribuição de recursos entre candidatos. Valores mais baixos sugerem maior concentração de recursos em poucos candidatos.\n\nEixo X: Tempo (anos ou eleições).\nEixo Y: Índice de Igualdade de Acesso a Recursos (IEAR).",
        unit: "IEAR",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Índice de Igualdade de Acesso a Recursos",
    },
    15: {
        title: "Índice de Diversidade Econômica entre Candidatos",
        indicator_purpose: "Mede a variedade no perfil econômico dos candidatos em uma eleição. Esse indicador ajuda a identificar se há predominância de candidatos de classes mais altas ou se há uma distribuição mais equilibrada de diferentes origens econômicas na política.",
        how_to_interpretate: "A evolução do índice pode refletir mudanças em políticas de inclusão e barreiras econômicas para a participação política. Valores mais altos indicam maior diversidade econômica entre os candidatos. Valores mais baixos sugerem que a maioria dos candidatos pertence a um mesmo grupo econômico.\n\nEixo X (horizontal): Tempo (anos ou eleições).\nEixo Y (vertical): Índice de Diversidade Econômica entre Candidatos (IDEC).",
        unit: "IDEC",
        party_indicator: false,
        "indicator_t1": true,
        xAxisLabel: "Ano",
        yAxisLabel: "Índice de Diversidade Econômica entre Candidatos",
    },
    16: {
        title: "Média e Mediana de Patrimônio da Classe Política",
        indicator_purpose: "Mede a evolução do patrimônio declarado dos políticos ao longo do tempo, ajudando a identificar padrões de concentração de riqueza na classe política. Esse indicador permite comparar a situação econômica dos políticos com a da população em geral e avaliar desigualdades.",
        how_to_interpretate: "Comparações com a renda média da população ajudam a avaliar o quão representativa a classe política é economicamente. Se a média for muito maior que a mediana, significa que há poucos políticos extremamente ricos elevando a média. Se ambas crescerem significativamente, pode indicar um aumento geral da riqueza da classe política.",
        unit: "Valor em real",
        party_indicator: false,
        "indicator_t1": false,
        xAxisLabel: "Ano",
        yAxisLabel: "Valor em real",
    },
}

module.exports = { indicatorsDetails }
