const UfForVotes = [
    { UF: undefined, label: "Brasil" },
    { UF: "AC", label: "Acre" },
    { UF: "AL", label: "Alagoas" },
    { UF: "AM", label: "Amazonas" },
    { UF: "AP", label: "Amapá" },
    { UF: "BA", label: "Bahia" },
    { UF: "CE", label: "Ceará" },
    { UF: "DF", label: "Distrito Federal" },
    { UF: "ES", label: "Espírito Santo" },
    { UF: "GO", label: "Goiás" },
    { UF: "MA", label: "Maranhão" },
    { UF: "MG", label: "Minas Gerais" },
    { UF: "MS", label: "Mato Grosso do Sul" },
    { UF: "MT", label: "Mato Grosso" },
    { UF: "PA", label: "Pará" },
    { UF: "PB", label: "Paraíba" },
    { UF: "PE", label: "Pernambuco" },
    { UF: "PI", label: "Piauí" },
    { UF: "PR", label: "Paraná" },
    { UF: "RJ", label: "Rio de Janeiro" },
    { UF: "RN", label: "Rio Grande do Norte" },
    { UF: "RO", label: "Rondônia" },
    { UF: "RR", label: "Roraima" },
    { UF: "RS", label: "Rio Grande do Sul" },
    { UF: "SC", label: "Santa Catarina" },
    { UF: "SE", label: "Sergipe" },
    { UF: "SP", label: "São Paulo" },
    { UF: "TO", label: "Tocantins" },
    { UF: "VT", label: "Voto de Trânsito" },
    { UF: "ZZ", label: "Exterior" },
]

module.exports = UfForVotes
