openapi: 3.0.0
info:
  title: Candidate Filters API
  version: 1.0.0
  description: API para obter filtros de candidatos.
servers:
  - url: http://localhost:7000
paths:
  /noauth/candidate/get-filters:
    get:
      summary: Obter filtros de candidatos
      description: Retorna os filtros disponíveis para candidatos.
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      cargos:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            nome:
                              type: string
                              example: "Engenheiro"
                      generos:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            nome:
                              type: string
                              example: "Masculino"
                      estados:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            nome:
                              type: string
                              example: "São Paulo"
                  message:
                    type: string
                    example: "Dados buscados com sucesso."
        '400':
          description: Requisição inválida
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  data:
                    type: object
                    example: {}
                  message:
                    type: string
                    example: "Erro ao buscar os filtros dos candidatos"
